### PR TITLE
initial implemenation of NeoKey_1x4

### PR DESCRIPTION
**Pull request by gmparis**
Hi All. I wanted CircuitPython support for this board. dastels suggested I write it myself. It was a bit difficult getting my head around the Seesaw, but fortunately I didn't need much of its capability. This code owes much to the Arduino code and to Dean's other Seesaw modules. I hope you find it useful. --Greg

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
Hi Greg, thanks for the code! I think this would be better done as a separate library because its for a specific seesaw product. There is a guide for it here: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library

@ladyada Do we have a guide in the works for this?

It may be interesting to @dhalbert as well who is establishing a key API for native internal use too in PR: https://github.com/adafruit/circuitpython/pull/4891 Ideally this library would share the same API.

**Comment by gmparis** [comment]
Hi @tannewt. It's making more sense to me now. Being unfamiliar with seesaw, I thought things like seesaw.neopixel and seesaw.keyboard are there for support of devices that could be connected to a seesaw. This seemed like just one more. If it should be a separate library, can it still keep the seesaw inheritance and still use the seesaw.neopixel?

**Comment by tannewt** [comment]
@gmparis, yup you can still inherit and use neopixel if you like. You'll just have this library as a dependency of the other.

**Comment by gmparis** [comment]
Not sure I can make it look much like that PR, since keypad does scanning keys in the background. I modeled my CP code after the Arduino code, which expects a typical main loop. Quite different from event queues, but I'll take another look. Also, it was pointed out to me that there is already a seed of work on this at Adafruit_CircuitPython_NeoKey, so I'll work from that instead of the Seesaw library. Thanks for the guidance.

**Pull request closed without merging**
